//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable FieldCanBeMadeReadOnly.Local
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Global
namespace NeoVastLib
{
    using System;

    public sealed partial class AdIdAttribute : VAttribute
    {
        public AdIdAttribute(object value) : base("adId", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("adId", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class AdSlotIdAttribute : VAttribute
    {
        public AdSlotIdAttribute(object value) : base("adSlotId", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("adSlotId", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class AdTypeAttribute : VAttribute
    {
        public AdTypeAttribute(object value) : base("adType", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("adType", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class AllowMultipleAdsAttribute : VAttribute
    {
        public AllowMultipleAdsAttribute(object value) : base("allowMultipleAds", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("allowMultipleAds", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class ApiFrameworkAttribute : VAttribute
    {
        public ApiFrameworkAttribute(object value) : base("apiFramework", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("apiFramework", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class AssetHeightAttribute : VAttribute
    {
        public AssetHeightAttribute(object value) : base("assetHeight", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("assetHeight", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class AssetWidthAttribute : VAttribute
    {
        public AssetWidthAttribute(object value) : base("assetWidth", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("assetWidth", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class AuthorityAttribute : VAttribute
    {
        public AuthorityAttribute(object value) : base("authority", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("authority", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class BitrateAttribute : VAttribute
    {
        public BitrateAttribute(object value) : base("bitrate", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("bitrate", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class BrowserOptionalAttribute : VAttribute
    {
        public BrowserOptionalAttribute(object value) : base("browserOptional", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("browserOptional", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class CodecAttribute : VAttribute
    {
        public CodecAttribute(object value) : base("codec", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("codec", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class ConditionalAdAttribute : VAttribute
    {
        public ConditionalAdAttribute(object value) : base("conditionalAd", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("conditionalAd", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class CreativeTypeAttribute : VAttribute
    {
        public CreativeTypeAttribute(object value) : base("creativeType", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("creativeType", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class CurrencyAttribute : VAttribute
    {
        public CurrencyAttribute(object value) : base("currency", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("currency", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class DeliveryAttribute : VAttribute
    {
        public DeliveryAttribute(object value) : base("delivery", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("delivery", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class DurationAttribute : VAttribute
    {
        public DurationAttribute(object value) : base("duration", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("duration", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class EventAttribute : VAttribute
    {
        public EventAttribute(object value) : base("event", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("event", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class ExpandedHeightAttribute : VAttribute
    {
        public ExpandedHeightAttribute(object value) : base("expandedHeight", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("expandedHeight", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class ExpandedWidthAttribute : VAttribute
    {
        public ExpandedWidthAttribute(object value) : base("expandedWidth", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("expandedWidth", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class FallbackOnNoAdAttribute : VAttribute
    {
        public FallbackOnNoAdAttribute(object value) : base("fallbackOnNoAd", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("fallbackOnNoAd", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class FileSizeAttribute : VAttribute
    {
        public FileSizeAttribute(object value) : base("fileSize", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("fileSize", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class FollowAdditionalWrappersAttribute : VAttribute
    {
        public FollowAdditionalWrappersAttribute(object value) : base("followAdditionalWrappers", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("followAdditionalWrappers", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class HeightAttribute : VAttribute
    {
        public HeightAttribute(object value) : base("height", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("height", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class IdAttribute : VAttribute
    {
        public IdAttribute(object value) : base("id", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("id", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class IdRegistryAttribute : VAttribute
    {
        public IdRegistryAttribute(object value) : base("idRegistry", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("idRegistry", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class LanguageAttribute : VAttribute
    {
        public LanguageAttribute(object value) : base("language", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("language", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class MaintainAspectRatioAttribute : VAttribute
    {
        public MaintainAspectRatioAttribute(object value) : base("maintainAspectRatio", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("maintainAspectRatio", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class MaxBitrateAttribute : VAttribute
    {
        public MaxBitrateAttribute(object value) : base("maxBitrate", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("maxBitrate", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class MediaTypeAttribute : VAttribute
    {
        public MediaTypeAttribute(object value) : base("mediaType", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("mediaType", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class MinBitrateAttribute : VAttribute
    {
        public MinBitrateAttribute(object value) : base("minBitrate", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("minBitrate", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class MinSuggestedDurationAttribute : VAttribute
    {
        public MinSuggestedDurationAttribute(object value) : base("minSuggestedDuration", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("minSuggestedDuration", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class ModelAttribute : VAttribute
    {
        public ModelAttribute(object value) : base("model", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("model", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class OffsetAttribute : VAttribute
    {
        public OffsetAttribute(object value) : base("offset", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("offset", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class ProgramAttribute : VAttribute
    {
        public ProgramAttribute(object value) : base("program", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("program", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class PxRatioAttribute : VAttribute
    {
        public PxRatioAttribute(object value) : base("pxratio", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("pxratio", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class RenderingModeAttribute : VAttribute
    {
        public RenderingModeAttribute(object value) : base("renderingMode", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("renderingMode", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class RequiredAttribute : VAttribute
    {
        public RequiredAttribute(object value) : base("required", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("required", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class ScalableAttribute : VAttribute
    {
        public ScalableAttribute(object value) : base("scalable", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("scalable", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class SequenceAttribute : VAttribute
    {
        public SequenceAttribute(object value) : base("sequence", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("sequence", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class SkipOffsetAttribute : VAttribute
    {
        public SkipOffsetAttribute(object value) : base("skipoffset", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("skipoffset", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class TypeAttribute : VAttribute
    {
        public TypeAttribute(object value) : base("type", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("type", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class VariableDurationAttribute : VAttribute
    {
        public VariableDurationAttribute(object value) : base("variableDuration", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("variableDuration", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class VendorAttribute : VAttribute
    {
        public VendorAttribute(object value) : base("vendor", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("vendor", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class VersionAttribute : VAttribute
    {
        public VersionAttribute(object value) : base("version", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("version", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class WidthAttribute : VAttribute
    {
        public WidthAttribute(object value) : base("width", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("width", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class XmlEncodedAttribute : VAttribute
    {
        public XmlEncodedAttribute(object value) : base("xmlEncoded", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("xmlEncoded", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class XPositionAttribute : VAttribute
    {
        public XPositionAttribute(object value) : base("xPosition", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("xPosition", value, this.validationFailureMessage);
            }
        }
    }

    public sealed partial class YPositionAttribute : VAttribute
    {
        public YPositionAttribute(object value) : base("yPosition", value)
        {
            if (!this.Validate())
            {
                throw new InvalidVastAttributeException("yPosition", value, this.validationFailureMessage);
            }
        }
    }
}